/* Automatically generated by './build/bin/build-entry.js' */

// import CubeTable from './CubeTable/src'
// import SearchBar from './SearchBar/src'
import MaxHeight from './MaxHeight/src'

const components = [
  MaxHeight
]

const install = function(Vue, opts = {}) {
  components.forEach(component => {
    Vue.component(component.name, component)
  })
}

/* istanbul ignore if */
if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue)
}

export default {
  version: '0.0.51',
  install,
  MaxHeight
}
